name: Go CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Update to the latest version to support Node 20

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.8  # Updated to the specified Go version

      - name: Install dependencies
        run: go mod download

      - name: Run tests with coverage
        run: go test -v -coverprofile=coverage.txt ./...

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: coverage.txt
          token: ${{ secrets.CODECOV_TOKEN }}  # Add your Codecov token in GitHub Secrets
          flags: unittests
          name: codecov-coverage
          fail_ci_if_error: true